### ISSUE TITLE
We should collect a human-readable journal and not the binary journals

### ISSUE THREAD

**Issue by trown** [redhat-openstack/ansible-role-tripleo-collect-logs#2] opened 2016-06-20 13:32 UTC
The binary journal is not readable from the web, so we should instead collect `jouralctl` output to a file, and not collect the binary journals in /var/log/journal.

**Comment by HarryRybacki-zz** [comment] 2016-09-07 15:02
@trown do you know if this is still an issue or if someone solved it? If not I'll jump on it soon.

**Comment by trown** [comment] 2016-09-07 18:44
@HarryRybacki It does not look like there is anything collecting all journal output, there is collecting from failed services though:
https://github.com/redhat-openstack/ansible-role-tripleo-collect-logs/blob/master/tasks/collect.yml#L31-L34

not sure if that is enough or not...

**Comment by HarryRybacki-zz** [comment] 2016-09-26 14:39
@trown who would we ask to determine an answer to ^^? I'm happy to add the functionality if it's helpful for debugging builds.

**Comment by trown** [comment] 2016-09-26 15:04
@HarryRybacki I wonder how many bytes that adds to the log collection for each job... IMO what we have is fine, as services are still logging to their own files in /var/log. When/if services start to **only** log to the journal, we would need to revisit this.

**Comment by apevec** [comment] 2016-10-28 08:45
There is still useful system-wide logging in the journal and plain copying binary journal is not good enough, see https://github.com/redhat-openstack/ansible-role-tripleo-collect-logs/issues/7

Also looks like tripleo is reconfiguring journal to not log to syslog? /var/log/messages looks rather empty after journal reconfiguration in recent jobs so we really need full journal properly collected.

**Comment by apevec** [comment] 2016-10-28 08:47
I propose to close this one as duplicate of issue #7

**Closed as completed by apevec** 2016-10-28 08:47 UTC
